### ISSUE TITLE
DateTime.parse()

### ISSUE THREAD

**Issue by daanwissing** [SpiritIT/timezonecomplete#15]
A nice feature: parsing a string (e.g. 21-10-2014) to a DateTime. The exact format can be given by using the LDML Date Format Pattern (http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Format_Patterns) to decide which part means what. For example: 
```typescript
var euDate = timezonecomplete.parse("10-12-2014","dd-MM-yyyy"); // Creates date at 10th of December 2014
var usDate = timezonecomplete.parse("10-12-2014","MM-dd-yyyy"); // Creates date at 12th of October 2014
```

**Comment by rogierschouten** [comment]
Implemented in 1.24.0
