### ISSUE TITLE
Bower installation and dependencies

### ISSUE THREAD

**Issue by rikkertkoppes** [SpiritIT/timezonecomplete#18]
Hi guys, first external issue, @poelstra will bring vlaai.

Had some issues while using this project

- bower is not able to find the package
- you claim to have removed the timezone-js dependency in 1.4.4 (c2ce93b77b7fc46e4a34ac3435857b95917f0f7f), however there are still a lot of references:
    - https://github.com/SpiritIT/timezonecomplete/search?utf8=%E2%9C%93&q=timezone-js
    - specifically: https://github.com/SpiritIT/timezonecomplete/blob/master/dist/timezonecomplete.js#L4-L13 

If I manually (eewk) remove all timezone-js references in the distribution, stuff works. This was tested in an AMD environment, judging by the code, stuff probably just works in a browser global situation (passing undefined in the factory).

Lastly, I'd assume that just cloning the repo and opening `examples/index.html` in the browser should "just work", however, the path to the dist is wrong. Either

- Change the `examples/index.html` file: `<script src="../dist/timezonecomplete.js"></script>`
- Duplicate the distribution file in the examples folder

Cheers!

**Comment by rogierschouten** [comment]
Closing this for now as most issues are solved. Please feel free to open a new issue for each remaining item you still would like to be solved.
