### ISSUE TITLE
why is sourcemap cruft included?

### ISSUE THREAD

**Issue by rikkertkoppes** [SpiritIT/timezonecomplete#20]
https://github.com/SpiritIT/timezonecomplete/blob/master/dist/timezonecomplete.js#L8627

Why is the sourcemap consumer there? Seems like a lot of extra baggage to me

**Comment by rogierschouten** [comment]
Solved in commit 1f592be

It is there to provide TypeScript stack traces, which is mainly used for the unittests. I moved the source-map-support to the unittests and made it a dev-dependency.

**Comment by rogierschouten** [comment]
Released version 1.11.2
