### ISSUE TITLE
addLocal performance troubles

### ISSUE THREAD

**Issue by justinrleblanc** [SpiritIT/timezonecomplete#26]
First: many thanks to Rogier for the courage to attempt a unified library for conversion of all time units for all locales around the entire globe; it must take some supernatural wisdom to make it work without a single incorrect conversion :)

Unfortunately, for my need, I don't think I will be able to make use of your hard work. I need to do date arithmetic to traverse thousands of time points in sequence, but the addLocal function does not perform well enough for me to do so in a reasonable amount of time.

I did some testing with a simple loop such as this:
        for(idx_datapoint = 0;idx_datapoint < count;idx_datapoint++){
               date = date.addLocal(interval_minutes, tc.TimeUnit.Minute)
        }

here are my performance results by making various modifications to the addLocal function:
- no modifications: ~14 seconds
- replaced the return new DateTime with inline performance of the constructor activity and returning the self-reference: ~10 seconds
- above + use a hard-coded timestamp value instead of performing normalization: ~2-3 seconds
- above + skip the _addToTimeStruct call: ~0.2-0.3 seconds
- return self-reference only (no other activity in addLocal): ~0.02-0.03 seconds

As you can see, each activity in addLocal results in a magnitude increase in cost of execution time. This results in an overall performance over the necessary datapoints that is not workable for an application that needs to be somewhat user interactive, especially considering that such loop is itself only one part of an operation that is executed multiple times in order to get a useful result.

If you have a reasonable plan to optimize all of the above, I could see donating somewhat in order to be able to use it for my needs; until then, it will have to remain on the bookshelf.

**Comment by rogierschouten** [comment]
Hi @justinrleblanc thank you for trying and analyzing it.    Sure we could optimize it further - it has already gone through several optimizations.  The performance mainly depends on what you're trying to add and whether you are in a time zone that has Daylight Saving Time. 

For instance, adding years, months or days is relatively easy. Adding hours, minutes or seconds can be cheap or costly depending on whether they are multiples of e.g. 12 or 24.  In rare cases, we actually have to do a binary search on the answer.  Next to that, lots of performance can be gobbled up by conversions between UTC and local time (one way is easy, the other way is very hard).

Therefore, to optimize your case we would need to know whether the intervals you want to add have something in common. What does your dataset look like?

By the way (just checking), if you don't have a time zone or you are in a time zone without DST then the add() method is way faster than addLocal().

**Comment by rogierschouten** [comment]
In the meantime, I will already look into some of the bullets you mentioned. Thanks again for doing this.

**Comment by justinrleblanc** [comment]
Hello Rogier,
Thank you kindly for your prompt responses; I can tell that you very much care about the quality of what you produce.

If it helps, my datasets can be associated with any timezone, but are primarily in the United States, where most locales use DST. The intervals are commonly 15 minutes or one minute, though they can be greater or less, not usually more than one hour. The span is usually one year or less, though we were hoping at some point to analyze multiple  years.

Thank you for the suggestions; I may try, for the special case of non-DST locales, to optimize by using add instead of addLocal, but that will not suffice for the general case.

I await your discoveries regarding any potential performance improvements; thank you for willingness to try.

**Comment by rogierschouten** [comment]
I'm making progress.  What would be acceptable performance to you?

**Comment by justinrleblanc** [comment]
I would need to go through a minimum of 150000 datapoints in at most 10 seconds, but even that might be on the slow end.

For now I am using momentjs and completing the task in about 8 seconds.
I still stand by my pledge to donate if you manage to get to an interactive level of performance; I believe in the value of multiple alternatives in software, especially regarding differing levels of performance and accuracy.



Justin LeBlanc
Email: justin.r.leblanc@hotmail.com
Mobile: 530-919-3233


________________________________

**Comment by rogierschouten** [comment]
I've just pushed release 4.0.0 which includes the performance improvements.  I can now run 150,000 addLocal() calls in 6 seconds on my computer, using the script below.

```javascript
var tc = require("timezonecomplete");
var start = tc.nowUtc();
var zone = tc.zone("America/Chicago");
var dt = new tc.DateTime("2016-03-03T23:59:59.000", zone);
for (var i = 0; i < 150000; ++i) {
    dt = dt.addLocal(tc.minutes(15));
}
var end = tc.nowUtc();
console.log(end.diff(start).toString());
```

Can you maybe give me some feedback as to how it's working for you, or if there any other bottlenecks? If it still isn't fast enough maybe you can send me some example code of what it is you need to work well.

**Comment by rogierschouten** [comment]
Please note v5.0.0 is just out and now you need to also install the 'tzdata' module.
