### ISSUE TITLE
DST rule for Timezone

### ISSUE THREAD

**Issue by eatnlunch** [SpiritIT/timezonecomplete#30]
Is it possible using this module to look up the available DST rules for a given Timezone?

**Comment by rogierschouten** [comment]
There are three ways currently.

1. Repeatedly get the next DST transition moment using `TzDatabase.instance().nextDstChange(zoneName, unixUtcMillis)`. This returns unix UTC milliseconds. 
1. Read the raw data from the tzdata NPM module. This requires you to understand the IANA TZ database format.
1. Get processed data using `TzDatabase.instance().getZoneInfos(zoneName)` (which indicates which TZ database rule names are applicable for the zone at which period in history)  and then retrieve the DST rules using `TzDatabase.instance().getRuleInfos(ruleName)`.  A RuleInfo object encodes a rule of law to make DST changes.

To learn more about options 2 and 3, you may want to have a look at the file `src/lib/tz-database.ts` which has a lot of comments explaining all the data structures. 

If you give me more details about what it is you need, I may be able to give you an example or maybe extend timezonecomplete to make the information more accessible.

**Comment by eatnlunch** [comment]
Thanks for the quick response.
The ultimate would be for me to be able to have a utility function to pass in a Timezone string (such as 'America/Chicago' or any other valid TZ string) and get back the DST rule in effect for the current year, including begin/end data. 
I'll start by investigating options 2 and 3, thanks again.

**Comment by rogierschouten** [comment]
Actually using option 1 twice from start of the given year seems to fulfill your needs then?  Anyway I'll close this issue for now but feel free to reopen if needed.

**Comment by eatnlunch** [comment]
@rogierschouten , thanks for the assist. Option 1 got me what I needed for one task.
Now, I'm looking through the docs and trying to find something else I know there must be a method for, just not finding it.
What I'm now trying to find is two-fold:
1. the number of minutes difference from UTC a particular timezone is in, assuming NO DST
2. the number of minutes offset DST would apply if it were active.

Will this require digging through the tzdata db or do you have any convenience methods built-in that I could use?
Thanks again

**Comment by rogierschouten** [comment]
One thing to think about is that a time zone does not 'have' a DST or an offset in general. Throughout history, its laws have probably changed multiple times, and likely also during a year. So the only thing you can ask is what the offset and DST offset of a zone is _at a particular moment in time_. 

Here's how you get the offset including DST:
```javascript
var tc = require("timezonecomplete");
var dt = new tc.DateTime("2016-03-31 Europe/Amsterdam");
dt.offset(); // total offset including DST in minutes: 120
```
Here's how you get the offset without DST (note how the date is created):
```javascript
var tc = require("timezonecomplete");
var dt = new tc.DateTime("2016-03-31", tc.zone("Europe/Amsterdam without DST");
dt.offset(); // total offset excluding DST in minutes: 60
```

Another way of creating a zone and leaving out DST is this:
```javascript
var tc = require("timezonecomplete");
var dt = new tc.DateTime("2016-03-31", tc.zone("Europe/Amsterdam", false));
dt.offset(); // total offset excluding DST in minutes: 60
```

**Comment by rogierschouten** [comment]
Hi @eatnlunch,  I've just made a new release 5.3.0 with some convenience methods for you. I also made a small bugfix of something I encountered while trying out stuff for my previous message. 

```javascript
// Get the total offset from UTC including DST
new tc.DateTime("2016-03-31 Europe/Amsterdam").offsetDuration(); // 2 hours

// Get the standard offset from UTC excluding DST
new tc.DateTime("2016-03-31 Europe/Amsterdam").standardOffsetDuration(); // 1 hour
```

Both new methods return a Duration object so you don't have to worry what unit the result is in. Unfortunately I had to name them `xxxDuration()` to keep the regular `offset()` method backward compatible.

**Comment by eatnlunch** [comment]
Wow, thanks for this. I'll pull down the latest and give it a shot.
Thanks again

**Comment by eatnlunch** [comment]
This seems to work nicely, thanks again for the quick responses.
