### ISSUE TITLE
DateTime.format throws on unexpected symbols

### ISSUE THREAD

**Issue by mgroenhoff** [SpiritIT/timezonecomplete#34]
Currently the format function throws an error if the format contains "unexpected symbols" which should just be passed through as is.
```typescript
tc.now().format('F') // This throws because a single 'F' is not a symbol according to LDML tough two "FF" are
```
Is it possible to just replace the symbols that are known?

**Comment by rogierschouten** [comment]
Fixed and published as v5.4.5.
