### ISSUE TITLE
Bug: Parsing AM/PM always returns AM

### ISSUE THREAD

**Issue by bagrounds** [SpiritIT/timezonecomplete#35]
```js
const time_am = '2017-12-15 2:00AM'
const time_pm = '2017-12-15 2:00PM'
const format = 'YYYY-MM-dd h:mma' // 'a' is for AM/PM
tc.DateTime.parse(time_am, format).format(format)
// => '2017-12-15 2:00AM'
tc.DateTime.parse(time_pm, format).format(format)
// => '2017-12-15 2:00AM' (<- this should be PM)
```
```sh
$ node --version
v8.9.3
```
```sh
$ npm ls timezonecomplete
└── timezonecomplete@5.4.5
```

**Comment by rogierschouten** [comment]
Thank you for reporting this. It's fixed and published as v5.4.6.

Also I documented our level of support for various [LDML patterns](https://github.com/SpiritIT/timezonecomplete/blob/master/doc/LDML.md)

As you can see, there is still a bit of work to be done there. If you need anything else that is not supported, please let me know.
