### ISSUE TITLE
Incorrect DST Transitions

### ISSUE THREAD

**Issue by eric-corumdigital** [SpiritIT/timezonecomplete#50]
```
var tzd = tc.TzDatabase.instance();
tzd.nextDstChange('America/Detroit', 1612199681000); // 1615701600000
```

The stated transition time, in UTC, is one hour too early. We spring forward at 02:00 (to 03:00) (local), not at 01:00 (local).

The information in tzdata seems to be correct in that it says 02:00, but the interpretation by TzDatabase appears to be incorrect.

**Comment by rogierschouten** [comment]
Something is fishy, that is for sure (notice how 1AM becomes 2AM:

```typescript
var r1 = new tc.DateTime("2021-03-14T01:00:00 America/Detroit");
console.log(r1.toString()); // "2021-03-14T02:00:00 America/Detroit"
```

Still the question is what should your output be? is 1615701600000 UTC 1AM or 2AM local time because it is on the DST change moment and hence GMT-5 or GMT-4.  I will look into it

**Comment by rogierschouten** [comment]
Fixed in v5.11.3 
@eric-corumdigital  thank you for reporting this!

**Comment by rogierschouten** [comment]
Note to self: Current heuristic works for US but not in general; need an iterative algorithm instead of a heuristic to implement the nextDstChange function

**Comment by eric-corumdigital** [comment]
> Still the question is what should your output be? is 1615701600000 UTC 1AM or 2AM local time because it is on the DST change moment and hence GMT-5 or GMT-4. I will look into it

My interpretation is that the change moment is inclusive of the change. I have not read a formal definition of DST, but it would be odd to have one instant of 2AM and then jump to another hour (because that would be a zero-duration hour!).

**Comment by eric-corumdigital** [comment]
I will detail what I have observed in hopes it offers some clarity.

The offset transition (-5 to -4 hours) on March 14th at 02:00 local time occurs at 07:00 UTC. We can write the interval timeline where each interval is labeled with the local UTC offset.

```
     07
-5 ) | [ -4
```

I mean to show that from all time before to 07 (exclusive), the offset is -5, and from all time after (inclusive) the offset is -4.

Converting a UTC time to a local time is as easy as finding where the UTC time falls on this timeline and applying the labeled offset.

To convert a local time to a UTC time we have to invert the process. That is to say, we need the local interval timeline labeled with the correct inverted offsets. This can be found by converting the UTC transition time of 07 to the local time for each offset.

```
     02             03
+5 ) | [ undefined ) | [ +4
```

This shows that all local times up to 02 (exclusive) are converted to UTC time by adding 5 hours, and all local times after 03 (inclusive) are converted to UTC time by adding 4 hours. However, it also shows that all local times between 02 (inclusive) and 03 (exclusive) are undefined in UTC time (and even locally they have no meaning).

This same approach can be done for the next -4 hour to -5 hour transition also at 02:00 local time. This will occur at 06:00 UTC.

The UTC timeline is:
```
     06
-4 ) | [ -5
```

And so the local timeline must be:
```
  01        02
  |          |
) | [        |    +5
     +4/+5   |
+4         ) | [
```

This shows that for all times up to 01 (exclusive) the inverted offset is +4. From 01 (inclusive) to 02 (exclusive) the inverted offset may be either +4 or +5 (it is ambiguous; there are two answers). From 02 (inclusive) to all times after the inverted offset is +5.

While converting UTC to local time is a function, converting local time to UTC time is not. There may be zero, one, or two (or more, depending on how many transitions are intersected) UTC times for a local time. If we restrict "local time" to be valid local times (rather than just a date and time pair) then there are nonzero UTC times for a local time.

**Comment by rogierschouten** [comment]
thx @eric-corumdigital  
I am most concerned that my algorithm for reading the rules still is not watertight.  I have looked in the IANA C code for an example and I think I will need to port  that to JavaScript.   It will be quite a redesign of the TzDatabase class though and I simply don' t have time right now. It will take a while...

If you wanna have a stab at it, look in [IANA C Code (tar.gz)](https://data.iana.org/time-zones/releases/tzcode2021a.tar.gz)  in file localtime.c  function tzparse().  Not for the faint of heart. 


The main bug in timezonecomplete now is that the TZ rules have a transition time which can be either in local time (i.e. 2AM), standard offset time (i.e. 2AM expressed as GMT-5 regardless of summer/winter time),  or UTC time.   It is the local time which is almost impossible to calculate, because it depends on all other active rules - which is influenced by the zone lines as well. 

Let me know if you' d like to start working on it so we don' t do it both at the same time - I might have some time this weekend

**Comment by rogierschouten** [comment]
@eric-corumdigital FYI I am actively working on this now.  I'm telling you because I asked in prev post if you could work on it - avoid both of us working on it at the same time.

**Comment by eric-corumdigital** [comment]
Hello @rogierschouten 

Thanks for looking into the issue. Unfortunately, I cannot justify time to work on this unless it is shown the transition calculations are wrong for a NA time zone for a future date. Since your patch, they seem to be correct, in my limited testing.

If the situation changes I'll let you know.

**Comment by rogierschouten** [comment]
@eric-corumdigital  please try v5.12.0.  It was brain-melting but I think we have a more robust version now in several respects.
