### ISSUE TITLE
Install on Node.js missing tzdata as a dependency since 5.11.3

### ISSUE THREAD

**Issue by rogerweb** [SpiritIT/timezonecomplete#51]
My Node.js application has

```
"timezonecomplete": "^5.11.2",
```

as a dependency in `package.json` and I was always able to `npm install` and start the application just fine.

Since 5.11.3/5.11.4, a fresh `npm install` no longer adds `tzdata` as a dependency, so the application errors out when starting:

```
timezonecomplete.InvalidTimeZoneData: Timezonecomplete needs time zone data.
You need to install one of the tzdata NPM modules before using timezonecomplete
```

As per the documentation, in the Node.js usage section (https://github.com/SpiritIT/timezonecomplete#nodejs), the user is not required to manually install `tzdata`, right?

**Comment by rogierschouten** [comment]
Thank you for reporting @rogerweb !   Fixed and published as v5.11.5
