### ISSUE TITLE
unixTimestamp clarifications

### ISSUE THREAD

**Issue by alexelite** [SpiritIT/timezonecomplete#52]
I installed the latest version and I was playing around with unixtimestamp and could not find an explanation in the documentation for the following behavior.
```
var tc = require("timezonecomplete");
var amsterdamDate = new tc.DateTime(1388577599000, tc.zone("Europe/Amsterdam"));
var bucharestDate = new tc.DateTime(1388577599000, tc.zone("Europe/Bucharest"));
console.log(amsterdamDate.unixUtcMillis());//returns 1388573999000
console.log(bucharestDate.unixUtcMillis());//returns  1388570399000
```
In the documentation I found that DateTime constructor's parameters are:
```
unixTimestamp: number
milliseconds since 1970-01-01T00:00:00.000
Optional timeZone: TimeZone | null | undefined
```
and for unixUtcMillis() method:
```
Returns number
Milliseconds since 1970-01-01T00:00:00.000Z
```
To my understanding unixtimesptamp is universal time, no time zone, no daylight saving. 
So if the input is unixtimesptamp it should not change, only the representation for it based on local time offset, etc.
I notice there is a missing Z at the end of the description for DateTime constructor parameter.
Does this mean the input should be "corrected" by adding the local offset? But this offset is supposed to be accounted for by the library. 
Can you please clarify if this is the desired effect, and if so, a small note in the constructor documentation is needed.
Thank you.

**Comment by alexelite** [comment]
I looked in the source code and there is a more clearer note there:
```
	 * Constructor
	 * @param unixTimestamp	milliseconds since 1970-01-01T00:00:00.000
	 * @param timeZone	the time zone that the timestamp is assumed to be in (usually UTC).
```
so the timestamp is supposed to be corrected with the proper time zone offset.

I guess the correct way to do it, is to enter the timestamp with UTC defined and convert it to proper time zone.
`var bucharestDate = new tc.DateTime(1388577599000, tc.utc()).convert(tc.zone("Europe/Bucharest"));`

**Comment by rogierschouten** [comment]
Hi @alexelite  yes you are right.  Next week I will be working on this package, so I will see if I can clarify it in the docs.  Thank you

**Comment by rogierschouten** [comment]
I updated the overview docs. Note that details can always be found in the [API Reference](https://rawcdn.githack.com/SpiritIT/timezonecomplete/master/doc/typedoc/globals.html) which is auto-generated from the method comments.

If you have any further questions, let me know.

**Comment by alexelite** [comment]
Thank you very much.
