### ISSUE TITLE
DateTime.valueOf and Duration.valueOf should return number type

### ISSUE THREAD

**Issue by blackwindforce** [SpiritIT/timezonecomplete#55]
https://github.com/SpiritIT/timezonecomplete/blob/72c83e49a1d39b403e5d2aba8c7b2a2752306c86/src/lib/datetime.ts#L1287-L1293

https://github.com/SpiritIT/timezonecomplete/blob/72c83e49a1d39b403e5d2aba8c7b2a2752306c86/src/lib/duration.ts#L743-L749

both `valueOf` should return number type

```ts
valueOf(): number;
```

**Comment by rogierschouten** [comment]
Thank you for reporting, fixed in v5.12.2
