### ISSUE TITLE
weekOfMonth Assert Failure

### ISSUE THREAD

**Issue by eric-corumdigital** [SpiritIT/timezonecomplete#56]
This more or less says all months have 31 days:
https://github.com/SpiritIT/timezonecomplete/blob/4e91e1c55ef48d65595f2c2b2d7ce2528e1ff7ec/src/lib/basics.ts#L376

Which then runs into this assert which says not all months have 31 days:
https://github.com/SpiritIT/timezonecomplete/blob/4e91e1c55ef48d65595f2c2b2d7ce2528e1ff7ec/src/lib/basics.ts#L364

This crashed on May 1st this year.

**Comment by rogierschouten** [comment]
Hi @eric-corumdigital. thank you for reporting this. It is fixed and published as v5.12.4.
