### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by MikeiLL** [SpiritIT/timezonecomplete#72]
When importing tc (into a React/NextJs project) using this syntax:

```
import tc from 'timezonecomplete';
```

Then `tc` is `undefined`.

It imports with the following syntax:

```
import * as tc from 'timezonecomplete`;
```

Then `tc` is there as expected, but there's a warning in the console:

```
instrument.js:108 ./node_modules/timezonecomplete/dist/lib/tz-database.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

Also tried initializing via webpack config, but the error persists.

Any suggestions?

**Comment by hoancea** [comment]
hi, @MikeiLL. apologies for the (very) late reply.

please check [this section of the README](https://github.com/SpiritIT/timezonecomplete?tab=readme-ov-file#webpack). if you add such a `webpack.ContextReplacementPlugin` to your webpack config for the `tzdata-*` modules you import, the webpack warning will go away. this has to do with webpack not liking dynamic imports of modules.

please reopen this issue if you run into further issues.
